name: Deploy to Cloud Foundry
on:
  push:
    paths:
    - 'BTP/cf_python/**'
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name : CF PUSH
        uses: rangulvers/cf-push@main
        with:
          appdir:  '/home/runner/work/SAP/SAP/BTP/cf_python/testapp/'
          api:      ${{ secrets.CF_API }}
          org:      ${{ secrets.CF_ORG }}
          space:    ${{ secrets.CF_SPACE }}
          username: ${{ secrets.CF_USERNAME }}
          password: ${{ secrets.CF_PASSWORD }}
          manifest: manifest.yml
          validate: true
