name: Deploy to Cloud Foundry
on:
  push:
    paths:
    - 'BTP/cf_python/**'
    
defaults:
  run:
    working-directory: "BTP/cf_python/test app"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rangulvers/cf-push@v1
        with:
          api:      ${{ secrets.CF_API }}
          org:      ${{ secrets.CF_ORG }}
          space:    ${{ secrets.CF_SPACE }}
          username: ${{ secrets.CF_USERNAME }}
          password: ${{ secrets.CF_PASSWORD }}
#           workingdir: /home/runner/work/cf_python_test_app/cf_python_test_app
          manifest: manifest.yml
          validate: true
